// app/ui/fal/App.tsx
import { useState } from 'react';

export default function App() {
  const models = [
    {
      name: "fal-mc",
      version: "0.2.1",
      desc: "Fal.ai client model"
    },
    {
      name: "fal-audio-gen-musical-memex", 
      version: "1.0.0",
      desc: "Musical generation model"
    }
  ];

  const [results, setResults] = useState<{[key: string]: string | null}>({});
  const [loading, setLoading] = useState<string[]>([]);

  async function callModel(modelName: string) {
    // Clear previous results for this model
    setResults(prev => ({ ...prev, [modelName]: null }));
    
    try {
      // Use MCP tool to invoke the model
      const result = await window.mcpApp.invokeTool(modelName);
      
      // Display result
      setResults(prev => ({ 
        ...prev, 
        [modelName]: JSON.stringify(result?.output || result || 'Result unavailable', null, 2) 
      }));
    } catch (error) {
      console.error(`Failed to call ${modelName}:`, error);
    } finally {
      setLoading(prev => prev.filter(m => m !== modelName));
    }
  }

  function handleModelClick(model: typeof models[0]) {
    if (!loading.includes(model.name)) {
      setLoading(prev => [...prev, model.name]);
    }
  }

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>Fal MCP Server</h1>
        <p style={styles.subtitle}>AI Model Server via fal.ai API</p>
      </header>

      {models.map(model => (
        <div 
          key={model.name}
          onClick={() => handleModelClick(model)}
          style={{
            ...styles.card,
            opacity: loading.includes(model.name) ? 0.7 : 1,
            cursor: loading.includes(model.name) ? 'not-allowed' : 'pointer'
          }}
        >
          <div style={styles.cardHeader}>
            <h3 style={styles.modelName}>{model.name}</h3>
            <span style={{
              ...styles.statusBadge,
              backgroundColor: loading.includes(model.name) 
                ? '#fef3c7' // amber
                : results[model.name] !== null 
                  ? '#d1fae5' // green
                  : '#dbeafe', // blue
              color: loading.includes(model.name) 
                ? '#92400e' 
                : results[model.name] !== null 
                  ? '#065f46' 
                  : '#1e40af'
            }}>
              {loading.includes(model.name) ? 'Running...' : 
               results[model.name] !== null ? 'Success' : 'Ready'}
            </span>
          </div>

          <p style={styles.description}>{model.desc}</p>

          <button 
            style={{
              ...styles.button,
              opacity: loading.includes(model.name) ? 0.5 : 1
            }}
            onClick={(e) => {
              e.stopPropagation();
              handleModelClick(model);
            }}
            disabled={loading.includes(model.name)}
          >
            Call Model
          </button>

          {results[model.name] !== null && (
            <div style={styles.output}>
              <strong>{model.name} Result:</strong>
              <pre style={styles.pre}>{results[model.name]}</pre>
            </div>
          )}
        </div>
      ))}

      {models.length === 0 && (
        <p style={styles.emptyMessage}>No models available yet. Checking connectivity...</p>
      )}
    </div>
  );
}

const styles: { [key: string]: React.CSSProperties } = {
  container: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    minHeight: '100vh',
    backgroundColor: '#f3f4f6',
    padding: '2rem 1rem'
  },
  header: {
    textAlign: 'center',
    marginBottom: '2rem',
    color: '#1f2937'
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: 'bold',
    marginBottom: '0.5rem',
    background: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent'
  },
  subtitle: {
    color: '#6b7280',
    fontSize: '1.1rem'
  },
  card: {
    backgroundColor: 'white',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1rem',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
    transition: 'transform 0.2s, box-shadow 0.2s'
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '0.5rem'
  },
  modelName: {
    margin: 0,
    flex: 1,
    color: '#374151'
  },
  statusBadge: {
    padding: '0.25rem 0.75rem',
    borderRadius: '9999px',
    fontSize: '0.85rem',
    fontWeight: 600,
    marginLeft: '0.75rem'
  },
  description: {
    margin: '0 0 1rem 0',
    color: '#6b7280',
    fontSize: '0.95rem'
  },
  button: {
    width: '100%',
    padding: '0.75rem',
    backgroundColor: '#667eea',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    fontWeight: 600,
    cursor: 'pointer'
  },
  output: {
    marginTop: '1rem',
    padding: '1rem',
    backgroundColor: '#f9fafb',
    border radius: '8px',
    overflowWrap: 'break-word'
  },
  pre: {
    margin: 0,
    backgroundColor: '#f3f4f6',
    padding: '0.5rem',
    borderRadius: '6px',
    whiteSpace: 'pre-wrap',
    fontSize: '0.875rem'
  },
  emptyMessage: {
    textAlign: 'center',
    color: '#6b7280'
  }
};

// app/ui/frappe_ui/App.vue
<template>
  <div>
    <h2 class="text-xl font-bold mb-3 text-blue-600">Available Models</h2>
    
    <!-- Model List Grid -->
    <div class="model-grid" v-if="models.length === 0">
      <div class="loading">Loading models...</div>
    </div>

    <div 
      class="model-card" 
      v-for="model in models" 
      :key="model.name"
      @click="invokeModel(model)"
    >
      <h3 class="model-name">{{ model.name }}</h3>
      
      <!-- Status badge -->
      <span 
        class="model-status" 
        :class="model.status === 'loaded' ? 'status-loaded' : 'status-loading'"
      >
        {{ model.status }}
      </span>

      <p class="text-sm text-gray-600 mt-1">{{ model.description || model.name }}</p>
      
      <!-- Result display -->
      <div class="result-box" v-if="model.output">
        <strong>{{ model.name }}:</strong>
        <pre>{{ model.output }}</pre>
      </div>
    </div>

    <div class="loading text-center mt-6" v-if="models.length === 0">
      Loading available models...
    </div>
  </div>
</template>

<script setup>
import { ref, reactive } from 'vue'

// Store models keyed by model_name
const models = reactive({})

// Available models for Fal AI API (based on your project)
const AVAILABLE_MODELS = [
  {
    name: "fal-mc",
    version: "0.2.1",
    source: "https://huggingface.co/fal/Airavata-40b-fp8/resolve/main/model.json"
  },
  {
    name: "fal-audio-gen-musical-memex",
    version: "1.0.0",
    source: "fal_audio_gen_musical_memex"
  }
]

// Initialize models
for (const m of AVAILABLE_MODELS) {
  models[m.name] = {
    name: m.name,
    description: m.source?.includes('huggingface') ? `Model from HuggingFace` : m.source || '',
    status: 'loaded', // Models available for use
    output: null
  }
}

// Invoke model via MCP or Fal Client endpoint
async function invokeModel(model) {
  models[model.name].output = ''
  models[model.name].status = 'running'
  
  try {
    // Call MCP tool to invoke model
    const name = model.name.replace(/-/g, '_')
    const result = await window.mcpApp.invokeTool(name) || 'Model invocation command not available in this session. MCP server may not support direct tool calls from browser yet.'
    
    models[model.name].output = JSON.stringify(result, null, 2)
    console.log(`${name} invoked`, result)
  } catch (error) {
    console.error(`Failed to invoke ${model.name}:`, error)
  }
  
  models[model.name].status = 'loaded'
}

</script>

<style scoped>
/* Sayhello-style card layout */
div { color: #065f46; font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; }

</style>
